Repository CS2113-AY1819S1-F09-2/main, pull requests merged in 2018-10, with the labels that each got.

#48 Create subfolders for commands & change, edit the order of imports
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/employee/EmployeeAddCommand.java
  src/seedu/addressbook/commands/employee/EmployeeListCommand.java
  src/seedu/addressbook/commands/member/MemberCommandResult.java
  src/seedu/addressbook/commands/member/MemberListCommand.java
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuCommandResult.java
  src/seedu/addressbook/commands/menu/MenuListCommand.java
  src/seedu/addressbook/commands/menu/MenuViewAllCommand.java
  src/seedu/addressbook/commands/order/OrderClearCommand.java
  src/seedu/addressbook/commands/order/OrderCommandResult.java
  src/seedu/addressbook/commands/order/OrderDeleteCommand.java
  src/seedu/addressbook/commands/order/OrderListCommand.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, type.enhancement

#50 Refactor: change RMS class name into Rms to follow the coding standard
  .gitignore
  Rms.txt
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/CommandResult.java
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuListCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/menu/Menu.java
  src/seedu/addressbook/data/menu/ReadOnlyMenus.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/storage/jaxb/AdaptedRms.java
  src/seedu/addressbook/ui/Formatter.java
  src/seedu/addressbook/ui/Gui.java
  src/seedu/addressbook/ui/MainWindow.java
  test/data/StorageFileTest/ValidData.txt
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: priority.low, severity.low, type.task

#75 Add Order feature implementation
  .gitignore
  Rms.txt
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/order/DraftOrderClearCommand.java
  src/seedu/addressbook/commands/order/DraftOrderConfirmCommand.java
  src/seedu/addressbook/commands/order/DraftOrderEditCustomerCommand.java
  src/seedu/addressbook/commands/order/DraftOrderEditDishCommand.java
  src/seedu/addressbook/commands/order/OrderAddCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/order/Dish.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
  src/seedu/addressbook/data/order/UniqueOrderList.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedDish.java
  src/seedu/addressbook/storage/jaxb/AdaptedOrder.java
Labels: priority.high, type.story

#86 implementation of more fields in Member class
  src/seedu/addressbook/commands/member/MemberAddCommand.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/member/MemberName.java
  src/seedu/addressbook/data/member/Points.java
  src/seedu/addressbook/data/member/ReadOnlyMember.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/storage/jaxb/AdaptedMember.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.completed

#87 Added Edit Employee command
  Rms.txt
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/employee/EmployeeAddCommand.java
  src/seedu/addressbook/commands/employee/EmployeeCommandResult.java
  src/seedu/addressbook/commands/employee/EmployeeDeleteCommand.java
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/commands/employee/EmployeeListCommand.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/employee/EditEmployeeDescriptor.java
  src/seedu/addressbook/data/employee/UniqueEmployeeList.java
  src/seedu/addressbook/parser/Parser.java
Labels: status.completed

#99 implementation of more member functions
  src/seedu/addressbook/commands/member/MemberDeleteCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/common/Name.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/member/MemberName.java
  src/seedu/addressbook/data/member/Points.java
  src/seedu/addressbook/data/member/ReadOnlyMember.java
  src/seedu/addressbook/data/member/UniqueMemberList.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedMember.java
  src/seedu/addressbook/ui/Formatter.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, status.completed

#88 Created Type attribute for Menu and changed Regex for Price
  Rms.txt
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuClearCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/commands/menu/MenuListCommand.java
  src/seedu/addressbook/commands/menu/MenuShowMainMenuCommand.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/menu/Menu.java
  src/seedu/addressbook/data/menu/Price.java
  src/seedu/addressbook/data/menu/ReadOnlyMenus.java
  src/seedu/addressbook/data/menu/Type.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedMenu.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: status.ongoing, status.review-pending

#101 Make some changes to the existing Ordering features
  Rms.txt
  src/seedu/addressbook/commands/order/DraftOrderConfirmCommand.java
  src/seedu/addressbook/commands/order/DraftOrderEditCustomerCommand.java
  src/seedu/addressbook/commands/order/DraftOrderEditDishCommand.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedOrder.java
  src/seedu/addressbook/storage/jaxb/AdaptedRms.java
Labels: priority.low, status.review-pending, type.enhancement

#85 add different sections to the Developer's Guide
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/images/Architecture.png
Labels: priority.high, status.completed

#102 Add Order Commands: set the points of Members to update
  Rms.txt
  src/seedu/addressbook/commands/order/DraftOrderConfirmCommand.java
  src/seedu/addressbook/data/Rms.java
Labels: priority.high, type.story

#94 Update stats functions
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/statistics/StatsMemberCommand.java
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
  src/seedu/addressbook/commands/statistics/StatsOrderCommand.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/menu/Menu.java
  src/seedu/addressbook/data/statistics/MemberDateTable.java
  src/seedu/addressbook/data/statistics/OrderDateTable.java
  src/seedu/addressbook/data/statistics/QuantityRevenuePair.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/DarkTheme.css
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.review-pending

#108 Fix statsmenu not retrieving orders correctly
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
Labels: status.completed

#107 Formatted LogicTest and put TestDataHelper into its own class
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
Labels: priority.medium, status.completed

#110 build.gradle: add shadowJar
  build.gradle
Labels: priority.high

#109 DeveloperGuide.adoc: add Logic Diagram and Implementation section
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/images/Architecture.png
  docs/images/LogicClassDiagram.png
Labels: priority.high, status.review-pending, type.task

#111 update git ignore
  .gitignore
Labels: severity.low, status.review-pending

#112 Update stats function including removal of deprecated codes
  Rms.txt
  src/seedu/addressbook/commands/statistics/StatsEmployeeCommand.java
  src/seedu/addressbook/commands/statistics/StatsHelpCommand.java
  src/seedu/addressbook/commands/statistics/StatsMemberCommand.java
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
  src/seedu/addressbook/commands/statistics/StatsOrderCommand.java
  src/seedu/addressbook/data/statistics/AsciiTable.java
  src/seedu/addressbook/data/statistics/MemberDateTable.java
  src/seedu/addressbook/data/statistics/OrderDateTable.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/ui/Gui.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.review-pending, type.enhancement

#114 Update DG (wm)
  docs/DeveloperGuide.adoc
Labels: priority.high, status.completed

#117 Clock In and Clock Out command update and formatting updates
  src/seedu/addressbook/commands/employee/EmployeeAddCommand.java
  src/seedu/addressbook/commands/employee/EmployeeClockInCommand.java
  src/seedu/addressbook/commands/employee/EmployeeClockOutCommand.java
  src/seedu/addressbook/commands/employee/EmployeeDeleteCommand.java
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/commands/employee/EmployeeListCommand.java
  src/seedu/addressbook/data/employee/Attendance.java
  src/seedu/addressbook/data/employee/EmployeeEmail.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedAttendance.java
Labels: priority.medium, severity.low, status.review-pending

#100 Update user guide for stats function
  docs/UserGuide.adoc
Labels: priority.high, status.completed

#120 Updates to developer guide.
  docs/DeveloperGuide.adoc
Labels: priority.high, severity.low, status.completed

#118 Updated User Guide after addition of new commands
  docs/UserGuide.adoc
Labels: priority.medium, severity.low, status.review-pending

#121 Add reposense config file
  .gitignore
  _reposense/config.json
Labels: priority.high, severity.high, status.review-pending

#122 Update UG based on review
  docs/UserGuide.adoc
Labels: priority.medium, severity.low, status.review-pending

#123 Fix reposense not able to generate report due to extra comma
  _reposense/config.json
Labels: priority.high, severity.high, status.completed

#127 Updated Project Portfolio and Developer Guide with UI section
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/diagrams/UiComponentClassDiagram.pptx
  docs/images/UiComponentClassDIagram.png
  docs/team/kianhong.adoc
Labels: priority.low, severity.low, status.completed

#125 add member tier field
  src/seedu/addressbook/commands/order/DraftOrderConfirmCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/member/MemberTier.java
  src/seedu/addressbook/data/member/ReadOnlyMember.java
  src/seedu/addressbook/storage/jaxb/AdaptedMember.java
Labels: priority.high, status.completed

#129 README.adoc: setup codacy badge
  README.adoc
Labels: priority.low, type.task

#130 Edited title to properly reflect name
  docs/team/kianhong.adoc
Labels: priority.low, severity.low, status.review-pending
