Repository CS2113-AY1819S1-F09-2/main, pull requests merged in 2018-11, with the labels that each got.

#134 Release v1.2.1
  src/seedu/addressbook/Main.java
Labels: priority.high, type.task

#133 Added proper tagging for project portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: priority.low, severity.low, status.review-pending

#132 Update stats function including addition of member tiers
  src/seedu/addressbook/commands/statistics/StatsEmployeeCommand.java
  src/seedu/addressbook/commands/statistics/StatsMemberCommand.java
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
  src/seedu/addressbook/data/statistics/MemberDateTable.java
  src/seedu/addressbook/data/statistics/OrderDateTable.java
Labels: priority.high, severity.medium, status.completed

#135 Updated Developer Guide and User Guide and Added Test cases
  Rms.txt
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/images/DataComponent.png
  docs/team/salsabil.adoc
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/data/menu/Price.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, status.review-pending

#136 Add px1099's portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/px1099.adoc
Labels: priority.high, status.review-pending, type.task

#131 Add WM portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/images/StorageClassDiagram.png
  docs/team/angwm.adoc
Labels: priority.low, severity.low, status.review-pending

#119 Addition to UGDG and KM's Portfolio
  docs/AboutUs.adoc
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/Ui.png
  docs/team/kangming.adoc
  src/seedu/addressbook/common/Messages.java
Labels: status.review-pending

#137 Changes to messages for invalid command formats
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/employee/EmployeeDeleteCommand.java
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/parser/Parser.java
Labels: priority.low, severity.low, status.completed

#138 View draft order price and include adding new order instructions
  docs/UserGuide.adoc
  docs/images/AddOrderInstruction.png
  src/seedu/addressbook/commands/order/DraftOrderConfirmCommand.java
  src/seedu/addressbook/commands/order/OrderAddCommand.java
  src/seedu/addressbook/commands/order/OrderDeleteCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
Labels: priority.medium, status.review-pending, type.enhancement

#139 Add test for ordering functionality
  src/seedu/addressbook/commands/order/DraftOrderEditDishCommand.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.ongoing, type.task

#142 List order: hide Member apply date field
  docs/UserGuide.adoc
  src/seedu/addressbook/data/member/ReadOnlyMember.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
Labels: priority.medium, severity.low, status.completed, type.bug

#173 Edited UserGuide
  docs/UserGuide.adoc
Labels: priority.low, severity.low, status.review-pending

#172 Fixed duplicate employee bug
  Rms.txt
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/employee/UniqueEmployeeList.java
Labels: priority.low, severity.low, status.completed

#176 fix issues #146, #161, #171
  docs/UserGuide.adoc
Labels: priority.low, status.completed

#179 Disable addressbook
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, type.task

#180 Clock in display
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/employee/EmployeeClockInCommand.java
  src/seedu/addressbook/commands/employee/EmployeeClockOutCommand.java
Labels: priority.low, severity.low, status.review-pending

#144 Fixed Bugs in the code and instructions in the User Guide
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/commands/menu/MenuShowMainMenuCommand.java
  src/seedu/addressbook/data/menu/MenuName.java
  src/seedu/addressbook/data/menu/Price.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, status.review-pending

#184 rename UiComponentClassDiagram file so it would appear on the DG
  docs/images/UiComponentClassDiagram.png
Labels: status.review-pending

#188 Removed original AB3 commands that are not needed.
  src/seedu/addressbook/commands/AddCommand.java
  src/seedu/addressbook/commands/ClearCommand.java
  src/seedu/addressbook/commands/DeleteCommand.java
  src/seedu/addressbook/commands/FindCommand.java
  src/seedu/addressbook/commands/ListCommand.java
  src/seedu/addressbook/commands/ViewAllCommand.java
  src/seedu/addressbook/commands/ViewCommand.java
  src/seedu/addressbook/parser/Parser.java
Labels: priority.low, severity.medium, status.completed

#189 Remove failed employee test cases
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: severity.low, type.bug

#190 Fixed two test cases that were not working
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
Labels: priority.low, severity.low, status.review-pending

#192 Added MenuRecommendationCommand
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/commands/menu/MenuRecommendationCommand.java
  src/seedu/addressbook/commands/menu/MenuShowMainMenuCommand.java
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
  src/seedu/addressbook/parser/Parser.java
Labels: status.review-pending

#185 Add two new fields for the member feature
  src/seedu/addressbook/commands/member/MemberAddCommand.java
  src/seedu/addressbook/commands/order/DraftOrderEditPointsCommand.java
  src/seedu/addressbook/common/Email.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/member/MemberEmail.java
  src/seedu/addressbook/data/member/MemberTier.java
  src/seedu/addressbook/data/member/Points.java
  src/seedu/addressbook/data/member/ReadOnlyMember.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedMember.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.review-pending

#196 Remove addressbook from project & remove clockin, clockout test cases
  README.adoc
  src/seedu/addressbook/commands/Command.java
  src/seedu/addressbook/commands/CommandResult.java
  src/seedu/addressbook/commands/ExitCommand.java
  src/seedu/addressbook/commands/employee/EmployeeCommandResult.java
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/commands/member/MemberAddCommand.java
  src/seedu/addressbook/commands/member/MemberCommandResult.java
  src/seedu/addressbook/commands/member/MemberDeleteCommand.java
  src/seedu/addressbook/commands/member/MemberListCommand.java
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuClearCommand.java
  src/seedu/addressbook/commands/menu/MenuCommandResult.java
  src/seedu/addressbook/commands/menu/MenuDeleteCommand.java
  src/seedu/addressbook/commands/menu/MenuFindCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/commands/menu/MenuListCommand.java
  src/seedu/addressbook/commands/menu/MenuRecommendationCommand.java
  src/seedu/addressbook/commands/menu/MenuShowMainMenuCommand.java
  src/seedu/addressbook/commands/menu/MenuViewAllCommand.java
  src/seedu/addressbook/commands/order/OrderCommandResult.java
  src/seedu/addressbook/commands/statistics/StatsEmployeeCommand.java
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
  src/seedu/addressbook/commands/statistics/StatsOrderCommand.java
  src/seedu/addressbook/common/Email.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/common/Name.java
  src/seedu/addressbook/data/AddressBook.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/employee/Attendance.java
  src/seedu/addressbook/data/employee/EmployeeAddress.java
  src/seedu/addressbook/data/employee/EmployeeEmail.java
  src/seedu/addressbook/data/employee/Timing.java
  src/seedu/addressbook/data/employee/UniqueAttendanceList.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/menu/MenuName.java
  src/seedu/addressbook/data/menu/Type.java
  src/seedu/addressbook/data/person/Address.java
  src/seedu/addressbook/data/person/Email.java
  src/seedu/addressbook/data/person/Name.java
  src/seedu/addressbook/data/person/Person.java
  src/seedu/addressbook/data/person/Phone.java
  src/seedu/addressbook/data/person/ReadOnlyPerson.java
  src/seedu/addressbook/data/person/UniquePersonList.java
  src/seedu/addressbook/data/tag/Tag.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/storage/jaxb/AdaptedEmployee.java
  src/seedu/addressbook/storage/jaxb/AdaptedMember.java
  src/seedu/addressbook/storage/jaxb/AdaptedMenu.java
  src/seedu/addressbook/storage/jaxb/AdaptedPerson.java
  src/seedu/addressbook/storage/jaxb/AdaptedRms.java
  src/seedu/addressbook/storage/jaxb/AdaptedTag.java
  src/seedu/addressbook/ui/Formatter.java
  src/seedu/addressbook/ui/MainWindow.java
  test/data/StorageFileTest/ValidData.txt
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
  test/java/seedu/addressbook/storage/StorageFileTest.java
Labels: priority.high, status.review-pending, type.task

#197 Standardise display command formats
  src/seedu/addressbook/commands/member/MemberAddCommand.java
  src/seedu/addressbook/commands/member/MemberListCommand.java
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuDeleteCommand.java
  src/seedu/addressbook/data/employee/ReadOnlyEmployee.java
  src/seedu/addressbook/data/menu/ReadOnlyMenus.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: severity.medium, status.review-pending

#198 Changed how EmployeeEditCommand works
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/data/employee/EditEmployeeDescriptor.java
  src/seedu/addressbook/data/employee/EmployeeAddress.java
  src/seedu/addressbook/data/employee/EmployeeEmail.java
  src/seedu/addressbook/data/employee/EmployeePhone.java
  src/seedu/addressbook/data/employee/EmployeePosition.java
  src/seedu/addressbook/parser/Parser.java
Labels: priority.medium, severity.low, status.review-pending

#200 add exceptions to handle overflow bugs in price
  src/seedu/addressbook/data/menu/Price.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.high, status.review-pending

#202 Updated PortFolio, User Guide and Developer Guide, removed Viewall Command and added test cases for menu
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/images/MainMenu.PNG
  docs/team/salsabiltasnia.adoc
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/menu/MenuViewAllCommand.java
  src/seedu/addressbook/data/employee/EditEmployeeDescriptor.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: status.completed, type.task

#205 Limit quantity of draftdish command
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/order/DraftOrderEditDishCommand.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.low, status.review-pending, type.enhancement

#204 Minor modifications to UI, UGDG and PPP
  docs/images/AddMember.png
  docs/images/ListOrder.png
  docs/images/OrderAfterRedemption.png
  docs/images/OrderBeforeRedemption.png
  docs/images/PointsEarned.png
  docs/images/Ui.png
  docs/team/kangmingtay.adoc
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/common/Messages.java
Labels: priority.medium, status.completed

#207 Fixed tests for clocking and clockout command and changed timing displays for both commands
  src/seedu/addressbook/commands/employee/EmployeeClockInCommand.java
  src/seedu/addressbook/commands/employee/EmployeeClockOutCommand.java
  src/seedu/addressbook/data/employee/Attendance.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
Labels: priority.high, severity.low, status.completed

#209 Make the Parser accept insensitive command word
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/logic/LogicTest.java
Labels: priority.low, status.review-pending, type.enhancement

#206 Cleanup the showAsText() methods of data classes
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/order/DraftOrderConfirmCommand.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/member/ReadOnlyMember.java
  src/seedu/addressbook/data/menu/Menu.java
  src/seedu/addressbook/data/menu/ReadOnlyMenus.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
  src/seedu/addressbook/ui/Formatter.java
Labels: priority.medium, status.review-pending, type.enhancement

#210 Improve draft dish command
  docs/UserGuide.adoc
  src/seedu/addressbook/commands/order/DraftOrderEditDishCommand.java
  src/seedu/addressbook/parser/Parser.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.medium, status.review-pending, type.enhancement

#201 add limit to currentPoints and totalPoints to prevent overflow
  src/seedu/addressbook/commands/member/MemberAddCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/member/Points.java
  src/seedu/addressbook/storage/jaxb/AdaptedMember.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
Labels: priority.high, status.completed

#211 Improve code quality based on IntelliJ and Codacy warnings
  docs/team/kangmingtay.adoc
  docs/team/salsabiltasnia.adoc
  src/seedu/addressbook/commands/HelpCommand.java
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/commands/menu/MenuListCommand.java
  src/seedu/addressbook/commands/menu/MenuRecommendationCommand.java
  src/seedu/addressbook/commands/menu/MenuShowMainMenuCommand.java
  src/seedu/addressbook/commands/statistics/StatsEmployeeCommand.java
  src/seedu/addressbook/commands/statistics/StatsMemberCommand.java
  src/seedu/addressbook/commands/statistics/StatsMenuCommand.java
  src/seedu/addressbook/commands/statistics/StatsOrderCommand.java
  src/seedu/addressbook/common/Email.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/common/Name.java
  src/seedu/addressbook/common/Utils.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/employee/Attendance.java
  src/seedu/addressbook/data/employee/Employee.java
  src/seedu/addressbook/data/employee/EmployeeAddress.java
  src/seedu/addressbook/data/employee/EmployeeEmail.java
  src/seedu/addressbook/data/employee/EmployeePhone.java
  src/seedu/addressbook/data/employee/EmployeePosition.java
  src/seedu/addressbook/data/employee/UniqueAttendanceList.java
  src/seedu/addressbook/data/employee/UniqueEmployeeList.java
  src/seedu/addressbook/data/member/Member.java
  src/seedu/addressbook/data/member/MemberTier.java
  src/seedu/addressbook/data/member/Points.java
  src/seedu/addressbook/data/member/UniqueMemberList.java
  src/seedu/addressbook/data/menu/Menu.java
  src/seedu/addressbook/data/menu/MenuName.java
  src/seedu/addressbook/data/menu/Price.java
  src/seedu/addressbook/data/menu/Type.java
  src/seedu/addressbook/data/menu/UniqueMenuList.java
  src/seedu/addressbook/data/order/Order.java
  src/seedu/addressbook/data/order/ReadOnlyOrder.java
  src/seedu/addressbook/data/order/UniqueOrderList.java
  src/seedu/addressbook/data/statistics/AsciiTable.java
  src/seedu/addressbook/data/statistics/MemberDateTable.java
  src/seedu/addressbook/data/statistics/OrderDateTable.java
  src/seedu/addressbook/data/statistics/ReadOnlyStats.java
  src/seedu/addressbook/data/tag/Tag.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/StorageFile.java
  src/seedu/addressbook/storage/jaxb/AdaptedAttendance.java
  src/seedu/addressbook/storage/jaxb/AdaptedMenu.java
  src/seedu/addressbook/storage/jaxb/AdaptedOrder.java
  src/seedu/addressbook/ui/Formatter.java
  src/seedu/addressbook/ui/MainWindow.java
  test/java/seedu/addressbook/common/UtilsTest.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.low, status.review-pending, type.task

#214 Added author tags, removed unused codes and updated PPP and UG and DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/salsabiltasnia.adoc
  src/seedu/addressbook/commands/menu/MenuAddCommand.java
  src/seedu/addressbook/commands/menu/MenuClearCommand.java
  src/seedu/addressbook/commands/menu/MenuCommandResult.java
  src/seedu/addressbook/commands/menu/MenuDeleteCommand.java
  src/seedu/addressbook/commands/menu/MenuFindCommand.java
  src/seedu/addressbook/commands/menu/MenuListByTypeCommand.java
  src/seedu/addressbook/commands/menu/MenuListCommand.java
  src/seedu/addressbook/commands/menu/MenuRecommendationCommand.java
  src/seedu/addressbook/commands/menu/MenuShowMainMenuCommand.java
  src/seedu/addressbook/common/Messages.java
  src/seedu/addressbook/data/Rms.java
  src/seedu/addressbook/data/menu/Menu.java
  src/seedu/addressbook/data/menu/MenuName.java
  src/seedu/addressbook/data/menu/Price.java
  src/seedu/addressbook/data/menu/ReadOnlyMenus.java
  src/seedu/addressbook/data/menu/Type.java
  src/seedu/addressbook/data/menu/UniqueMenuList.java
  src/seedu/addressbook/logic/Logic.java
  src/seedu/addressbook/parser/Parser.java
  src/seedu/addressbook/storage/jaxb/AdaptedMenu.java
  src/seedu/addressbook/ui/Formatter.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/parser/ParserTest.java
Labels: priority.high, status.review-pending, type.task

#212 Edit Kang Ming's PPP
  docs/UserGuide.adoc
  docs/team/kangmingtay.adoc
Labels: status.completed

#216 Remove merge conflict
  src/seedu/addressbook/data/Rms.java
Labels: priority.high, severity.low, type.bug

#215 Added author tags
  src/seedu/addressbook/commands/employee/EmployeeAddCommand.java
  src/seedu/addressbook/commands/employee/EmployeeClockInCommand.java
  src/seedu/addressbook/commands/employee/EmployeeClockOutCommand.java
  src/seedu/addressbook/commands/employee/EmployeeCommandResult.java
  src/seedu/addressbook/commands/employee/EmployeeDeleteCommand.java
  src/seedu/addressbook/commands/employee/EmployeeEditCommand.java
  src/seedu/addressbook/commands/employee/EmployeeListCommand.java
  src/seedu/addressbook/data/employee/Attendance.java
  src/seedu/addressbook/data/employee/EditEmployeeDescriptor.java
  src/seedu/addressbook/data/employee/Employee.java
  src/seedu/addressbook/data/employee/EmployeeAddress.java
  src/seedu/addressbook/data/employee/EmployeeEmail.java
  src/seedu/addressbook/data/employee/EmployeeName.java
  src/seedu/addressbook/data/employee/EmployeePhone.java
  src/seedu/addressbook/data/employee/EmployeePosition.java
  src/seedu/addressbook/data/employee/ReadOnlyEmployee.java
  src/seedu/addressbook/data/employee/Timing.java
  src/seedu/addressbook/data/employee/UniqueAttendanceList.java
  src/seedu/addressbook/data/employee/UniqueEmployeeList.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
Labels: priority.high, severity.low, status.completed

#219 Edited PPP, UG and Data Component Diagram
  docs/DeveloperGuide.adoc
  docs/Diagrams.pptx
  docs/UserGuide.adoc
  docs/images/DataComponent.png
  docs/images/MainMenu.PNG
  docs/team/salsabiltasnia.adoc
  src/seedu/addressbook/data/Rms.java
Labels: status.review-pending

#222 Update docs
  docs/UserGuide.adoc
  docs/images/statsemp.png
  docs/images/statsmember.png
  docs/images/statsmenu.png
  docs/images/statsorder.png
  docs/team/angwm.adoc
Labels: priority.high, severity.low, status.review-pending

#223 Updated Project Portfolio
  docs/team/kianhong95.adoc
Labels: priority.high, severity.low, status.review-pending

#217 EmployeeEmail now extends Email and EmployeePhone regex has been changed
  src/seedu/addressbook/common/Email.java
  src/seedu/addressbook/data/employee/EmployeeEmail.java
  src/seedu/addressbook/data/employee/EmployeePhone.java
  test/java/seedu/addressbook/logic/LogicTest.java
  test/java/seedu/addressbook/logic/TestDataHelper.java
Labels: priority.high, severity.low, status.review-pending

#224 more changes to DG
  docs/DeveloperGuide.adoc
  src/seedu/addressbook/common/Email.java
  src/seedu/addressbook/common/Name.java
  src/seedu/addressbook/data/member/ReadOnlyMember.java
Labels: status.review-pending

#225 Updated User Guide
  docs/UserGuide.adoc
Labels: priority.high, severity.low, status.review-pending

#228 Update px1099's portfolio
  build.gradle
  docs/stylesheets/asciidoctor.css
  docs/team/px1099.adoc
  docs/templates/_header.html.slim
Labels: priority.high, type.task

#226 made some changes to member section
  docs/UserGuide.adoc
Labels: status.ongoing

#230 Update README and ContactUs
  README.adoc
  docs/ContactUs.adoc
  docs/templates/_header.html.slim
Labels: priority.medium, type.task

#229 Updated constraints for Add Employee Command
  src/seedu/addressbook/data/employee/EmployeeAddress.java
  src/seedu/addressbook/data/employee/EmployeePosition.java
Labels: priority.high, severity.low, status.review-pending

#233 Update ui.png and version number
  docs/images/Ui.png
  src/seedu/addressbook/Main.java
Labels: priority.high, type.task

#234 Minor edits to the PPP
  docs/team/kianhong95.adoc
Labels: priority.high, severity.low, status.completed
